using System.Web;
using System.Web.Optimization;

namespace CodeLock
{
    public class BundleConfig
    {
        // For more information on bundling, visit http://go.microsoft.com/fwlink/?LinkId=301862
        public static void RegisterBundles(BundleCollection bundles)
        {
            bundles.Add(new ScriptBundle("~/bundles/jquery").Include("~/Scripts/jquery-{version}.js").Include("~/Scripts/jquery-{version}.min.js").Include("~/Script/jquery-3.1.1.intellisense.js").Include("~/assets/js/lib/moment.js"));
            bundles.Add(new ScriptBundle("~/bundles/modernizr").Include("~/Scripts/modernizr-*"));
            bundles.Add(new ScriptBundle("~/bundles/bootstrap").Include("~/Scripts/respond.js"));
            bundles.Add(new StyleBundle("~/assets/css").Include("~/assets/css/font-awesome.css").Include("~/assets/css/font-awesome-animation.css").Include("~/assets/css/material-design-iconic-font.css").Include("~/assets/css/bootstrap.css").Include("~/assets/css/animate.css").Include("~/assets/css/layout.css").Include("~/assets/css/components.css").Include("~/assets/css/widgets.css").Include("~/assets/css/plugins.css").Include("~/assets/css/pages.css").Include("~/assets/css/bootstrap-extend.css").Include("~/assets/css/common.css").Include("~/assets/css/responsive.css").Include("~/Content/bootstrap-datetimepicker.css").Include("~/assets/css/prettify.css").Include("~/assets/css/jquery-confirm.min.css"));
            bundles.Add(new ScriptBundle("~/assets/js").Include("~/assets/js/lib/jquery.js").Include("~/assets/js/lib/jquery-migrate.js").Include("~/assets/js/lib/bootstrap.js").Include("~/assets/js/lib/jquery.ui.js").Include("~/assets/js/lib/jquery-confirm.js").Include("~/assets/js/lib/jRespond.js").Include("~/assets/js/lib/jquerysession.js").Include("~/assets/js/lib/nav.accordion.js").Include("~/assets/js/lib/hover.intent.js").Include("~/assets/js/lib/hammerjs.js").Include("~/assets/js/lib/jquery.hammer.js").Include("~/assets/js/lib/jquery.fitvids.js").Include("~/assets/js/lib/scrollup.js").Include("~/assets/js/lib/smoothscroll.js").Include("~/assets/js/lib/jquery.slimscroll.js").Include("~/assets/js/lib/velocity.js").Include("~/assets/js/lib/velocity.js").Include("~/assets/js/lib/smart-resize.js").Include("~/assets/js/lib/icheck.js").Include("~/assets/js/lib/jquery.switch.button.js").Include("~/assets/js/lib/footable.min.js").Include("~/assets/js/lib/footable.sort.js").Include("~/assets/js/lib/footable.all.js").Include("~/assets/js/lib/jquery.dataTables.js").Include("~/assets/js/lib/dataTables.responsive.js").Include("~/assets/js/lib/dataTables.tableTools.js").Include("~/assets/js/lib/dataTables.scroller.js").Include("~/assets/js/lib/dataTables.colVis.js").Include("~/assets/js/lib/dataTables.colReorder.js").Include("~/assets/js/lib/dataTables.bootstrap.js").Include("~/assets/js/lib/tables-datatables-editor.js").Include("~/assets/js/lib/tables-datatables-extensions.js").Include("~/assets/js/lib/tables-datatables-sources.js").Include("~/assets/js/lib/dataTabels.buttons.print.min.js").Include("~/assets/js/lib/dataTables.buttons.min.js").Include("~/assets/js/lib/tableExport.js").Include("~/assets/js/lib/jquery.base64.js").Include("~/assets/js/lib/sprintf.js").Include("~/assets/js/lib/jspdf.js").Include("~/assets/js/lib/base64.js").Include("~/assets/js/lib/jquery.maskedinput.js").Include("~/assets/js/lib/jquery.validate.js").Include("~/assets/js/lib/jquery.form.js").Include("~/assets/js/lib/additional-methods.js").Include("~/assets/js/lib/jquery-cloneya.js").Include("~/assets/js/lib/selectize.js").Include("~/assets/js/lib/select2.full.js").Include("~/assets/js/lib/jquery.loadmask.js").Include("~/assets/js/lib/j-forms.js").Include("~/assets/js/lib/j-forms-validations.js").Include("~/assets/js/lib/jquery.loadmask.js").Include("~/assets/js/lib/moment.js").Include("~/Scripts/bootstrap-datetimepicker.js").Include("~/assets/js/lib/bootstrap-datepicker.js").Include("~/assets/js/lib/daterangepicker.js").Include("~/assets/js/lib/bootbox.js").Include("~/assets/js/lib/jquery.bootstrap.wizard.js").Include("~/assets/js/lib/prettify.js").Include("~/assets/js/apps.js").Include("~/Scripts/jqDevLogix.js").Include("~/Scripts/form-wizard.js").Include("~/Scripts/extension.js").Include("~/Scripts/common-event.js").Include("~/Scripts/jquery.validate*").Include("~/Scripts/expressive.annotations.validate.js"));
            BundleTable.EnableOptimizations = false;
        }
    }
}
